### ISSUE TITLE
How to create a custom method for EmuToString.fromString?

### ISSUE THREAD

**Issue by d-apps** [rknell/flutterEnumsToString#12]
Could you please help me creating my custom method of EnumToString.fromString? I am putting a dynamic but it seems it's not possible to use .values from it.

## My custom method:

```
 dynamic stringToEnum(dynamic enumData, String data){

  final result = EnumToString.fromString(enumData.values, data);

  return result;

}
```

## My code

```
enum DeliveryType { DELIVERY, PICKUP, BOTH }

DeliveryType deliveryType = DeliveryType.DELIVERY;

String delivery = EnumToString.parse(deliveryType);

stringToEnum(DeliveryType, delivery);
```

## Error:

```
E/flutter (20002): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: NoSuchMethodError: Class '_Type' has no instance getter 'values'.
E/flutter (20002): Receiver: DeliveryType
E/flutter (20002): Tried calling: values
E/flutter (20002): #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
E/flutter (20002): #1      stringToEnum (package:apploja/util/enums.dart:18:51)
E/flutter (20002): #2      main (package:apploja/main.dart:34:3)
E/flutter (20002): #3      _runMainZoned.<anonymous closure>.<anonymous closure> (dart:ui/hooks.dart:241:25)
E/flutter (20002): #4      _rootRun (dart:async/zone.dart:1184:13)
E/flutter (20002): #5      _CustomZone.run (dart:async/zone.dart:1077:19)
E/flutter (20002): #6      _runZoned (dart:async/zone.dart:1619:10)
E/flutter (20002): #7      runZonedGuarded (dart:async/zone.dart:1608:12)
E/flutter (20002): #8      _runMainZoned.<anonymous closure> (dart:ui/hooks.dart:233:5)
E/flutter (20002): #9      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:301:19)
E/flutter (20002): #10     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
E/flutter (20002): 
```

I don't undestand where this **T** come from and what is it in your method fromString.

**Comment by d-apps** [comment]
Problem solved, thanks anyway.

```
 T stringToEnum<T>(List<T> enumValues, String data){

  final result = EnumToString.fromString(enumValues, data);

  return result;

}
```

`print(stringToEnum(DeliveryType.values, delivery));`
